name: SMS on New Issue

on:
  issues:
    types: [opened]

jobs:
  send-sms:
    runs-on: ubuntu-latest
    steps:
      - name: Send SMS via Twilio
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: ${{ secrets.TWILIO_PHONE_NUMBER }}
          toPhoneNumber: ${{ secrets.MY_PHONE_NUMBER }}
          message: "New GitHub issue: ${{ github.event.issue.title }} - ${{ github.event.issue.html_url }}"
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
